// Generated by gencpp from file lab1/range.msg
// DO NOT EDIT!


#ifndef LAB1_MESSAGE_RANGE_H
#define LAB1_MESSAGE_RANGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <std_msgs/Float64.h>
#include <std_msgs/Float64.h>

namespace lab1
{
template <class ContainerAllocator>
struct range_
{
  typedef range_<ContainerAllocator> Type;

  range_()
    : header()
    , overall_range_min()
    , overall_range_max()  {
    }
  range_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , overall_range_min(_alloc)
    , overall_range_max(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::std_msgs::Float64_<ContainerAllocator>  _overall_range_min_type;
  _overall_range_min_type overall_range_min;

   typedef  ::std_msgs::Float64_<ContainerAllocator>  _overall_range_max_type;
  _overall_range_max_type overall_range_max;





  typedef boost::shared_ptr< ::lab1::range_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lab1::range_<ContainerAllocator> const> ConstPtr;

}; // struct range_

typedef ::lab1::range_<std::allocator<void> > range;

typedef boost::shared_ptr< ::lab1::range > rangePtr;
typedef boost::shared_ptr< ::lab1::range const> rangeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lab1::range_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lab1::range_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lab1::range_<ContainerAllocator1> & lhs, const ::lab1::range_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.overall_range_min == rhs.overall_range_min &&
    lhs.overall_range_max == rhs.overall_range_max;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lab1::range_<ContainerAllocator1> & lhs, const ::lab1::range_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lab1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::lab1::range_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lab1::range_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lab1::range_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lab1::range_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lab1::range_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lab1::range_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lab1::range_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b9a0dadad90f0aa59a1e41e20d3b947a";
  }

  static const char* value(const ::lab1::range_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb9a0dadad90f0aa5ULL;
  static const uint64_t static_value2 = 0x9a1e41e20d3b947aULL;
};

template<class ContainerAllocator>
struct DataType< ::lab1::range_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lab1/range";
  }

  static const char* value(const ::lab1::range_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lab1::range_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"std_msgs/Float64 overall_range_min\n"
"std_msgs/Float64 overall_range_max\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Float64\n"
"float64 data\n"
;
  }

  static const char* value(const ::lab1::range_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lab1::range_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.overall_range_min);
      stream.next(m.overall_range_max);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct range_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lab1::range_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lab1::range_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "overall_range_min: ";
    s << std::endl;
    Printer< ::std_msgs::Float64_<ContainerAllocator> >::stream(s, indent + "  ", v.overall_range_min);
    s << indent << "overall_range_max: ";
    s << std::endl;
    Printer< ::std_msgs::Float64_<ContainerAllocator> >::stream(s, indent + "  ", v.overall_range_max);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LAB1_MESSAGE_RANGE_H
